tz_dashboard:
    resource: "@AdminBundle/Resources/config/routing/dashboard.yml"
    prefix:   /

tz_niveau:
    resource: "@AdminBundle/Resources/config/routing/niveau.yml"
    prefix:   /niveau

tz_classe:
    resource: "@AdminBundle/Resources/config/routing/classe.yml"
    prefix:   /classe

tz_matiere:
    resource: "@AdminBundle/Resources/config/routing/matiere.yml"
    prefix:   /matiere

tz_salle:
    resource: "@AdminBundle/Resources/config/routing/salle.yml"
    prefix:   /salle

tz_recherche:
    resource: "@AdminBundle/Resources/config/routing/etudiant.yml"
    prefix:   /recherche

tz_note:
    resource: "@AdminBundle/Resources/config/routing/note.yml"
    prefix:   /note

tz_recherche_global:
    resource: "@AdminBundle/Resources/config/routing/search.yml"
    prefix:   /search

tz_discipline:
    resource: "@AdminBundle/Resources/config/routing/discipline.yml"
    prefix:   /discipline