# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.form.registration:
        class: App\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: fos_user_registration }
        arguments: ['%fos_user.model.user.class%']

    #    App\Controller\RegistrationController:
    #        arguments:
    #            $formFactory: '@fos_user.registration.form.factory'

    App\Services\EntityServices:
        autowire: false
        public: false
        arguments: ['@doctrine.orm.entity_manager','@service_container']

    App\Controller\User\RegistrationController:
        decorates: fos_user.registration.controller
        tags:
            - { name: controller.service_arguments}
        arguments:
            - '@event_dispatcher'
            - '@fos_user.registration.form.factory'
            - '@fos_user.user_manager'
            - '@security.token_storage'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
